### ISSUE TITLE
Where to place config info when using ReST?

### ISSUE THREAD

**Issue by deeplook** [executablebooks/sphinx-thebe#16]
@choldgraf I want to use sphinx-thebe with ReST, but I'm missing any information where to place config information about `binderOptions` and `kernelOptions`.

**Comment by choldgraf** [comment]
hey @deeplook - these options are all configured automatically from the configuration of your repository that you put in `conf.py`:

https://github.com/executablebooks/sphinx-thebe/blob/master/sphinx_thebe/__init__.py#L97

see the configuration page for reference:

https://sphinx-thebe.readthedocs.io/en/latest/configure.html

does that not work for you?

**Comment by deeplook** [comment]
@choldgraf I had seen that configuration page, but it has some potential to confuse people, like me, as it does not mention `conf.py` anywhere. And in the [last section](https://sphinx-thebe.readthedocs.io/en/latest/configure.html#configuration-reference) it says: "Here’s a reference of all of the configuration values avialable to sphinx-thebe.", but misses `codemirror-theme` from a section above.

After `pip install sphinx_thebe` and equivalent edits in my `conf.py` I see no editable cells after running `make html`:

```python
extensions = [
    # ...
    'sphinx_thebe'
]

thebe_config = {
    "repository_url": "https://github.com/my/repo",
    "repository_branch": "master",
    "selector": "div.thebe",
}
```

and this in `hello.rst`:

```
.. code-block:: python
   :class: thebe
   print("Hello World!")
```

Also, the config field names seem to be named differently from `thebelab` which I have tested ok briefly before.

**Comment by choldgraf** [comment]
@deeplook - you're right, I think that we can improve the documentation here and potentially reduce some confusion around having multiple configuration patterns for the same thing. 

I've also opened up https://github.com/executablebooks/sphinx-thebe/issues/17 to discuss standardizing the configuration value names 👍

**Comment by deeplook** [comment]
Can you point me to an existing example using ReST, similar to my description above?

**Comment by choldgraf** [comment]
Well right now I don't believe it is possible to configure `thebe` from within rST, the only configuration comes via the `conf.py` configuration. :-/

what's the thing you're trying to do that you cannot accomplish with `conf.py` configuration? That might be your only option until we can document / expand the configuration (e.g. via #17)

**Comment by deeplook** [comment]
I am ok with `conf.py`, I just wish it would work. ;)

**Comment by choldgraf** [comment]
me too 😬 sorry - this is a young package so still working out the kinks!

**Comment by deeplook** [comment]
Funny, but I found out that it actually works after I add this button to the ReST source:

```
.. thebe-button:: Click me!
```

But after I click on the button the code cell styling (in my case set by `sphinx_rtd_theme` gets modified quite a bit), see GIF.

![sphinx_thebe](https://user-images.githubusercontent.com/1001778/96998250-695ab600-1533-11eb-8393-b94880563373.gif)

**Comment by choldgraf** [comment]
yep - that is to be expected, it uses CodeMirror for the interactive cells, which apply a different styling etc. You can try modifying either with other themes or by applying your own CSS to the site.

Do you think this issue can be closed?

**Comment by deeplook** [comment]
Feel free to close it. Maybe the documentation issue can be handled separately (?).

**Comment by choldgraf** [comment]
yeah - for sure there is still more to do!
