### ISSUE TITLE
Consider implementing a per-page asset inclusion

### ISSUE THREAD

**Issue by akhmerov** [executablebooks/sphinx-thebe#22]
Since sphinx 3.5 it is possible to include js/css assets only as necessary (sphinx-doc/sphinx#8631). Consider supporting this functionality.

It may, however, be out of scope since the sphinx implementation is based on the nodes that page contains, and sphinx-thebe operates on the level of javascript selectors.

**Comment by choldgraf** [comment]
I think this is a great idea as long as the implementation is straightforward

**Comment by choldgraf** [comment]
I think that this one is no-longer needed, since we now lazily load Thebe by default. If there's still demand for per-page inclusion, happy to re-visit this one
